### ISSUE TITLE
Official launch

### ISSUE THREAD

**Issue by Juanlu001** [python-spain/PyConES-2019#2]
* [x] Integrate with mailchimp
* [x] Remove links to sponsor leaflet if it's not available yet
* [x] Fix http/https
* [x] Make contact way more explicit
* [x] CNAME to 2019.es.pycon.org
* [x] Tweet, email announcement

**Comment by Juanlu001** [comment]
cc @Daniel-Domene @Zuriich

**Comment by Zuriich** [comment]
- [ ]  Integrate with mailchimp
- [x]  Remove links to sponsor leaflet if it's not available yet
- [x]  Fix http/https
- [x]  Make contact way more explicit
- [ ]  CNAME to 2019.es.pycon.org
- [ ]  Tweet, email announcement

**Comment by Juanlu001** [comment]
Asked CNAME to @jcea.

**Comment by Juanlu001** [comment]
We'll make the official announcement when the sponsors leaflet is online.
