### ISSUE TITLE
Enlace venta de entradas

### ISSUE THREAD

**Issue by Juanlu001** [python-spain/PyConES-2019#23]
Como pronto va a salir la venta de entradas, necesitamos tener un link bien visible a la página de Eventbrite, o incluso incrustar el formulario.

@Daniel-Domene aquí tal vez necesitemos tu colaboración

**Comment by Unaipg** [comment]
Como queremos hacer esto? 

Se me ocurre que podríamos poner un link en el header, donde las imágenes grandes que ahora pone `Alicante, España. Octubre 04-06 2019` y quizá añadir otra fila entre los 3 artículos que salen ahora y los keynoters donde poner la noticia. O solo la fila siendo lo primero pero sin ponerlo en el header, para que no esté repetido justo al lado.

**Comment by Juanlu001** [comment]
No lo visualizo del todo, ¡lo dejo en vuestras manos!

**Comment by Daniel-Domene** [comment]
Confío plenamente en tu criterio Unai. Tú tienes más experiencia en esto.

**Comment by Daniel-Domene** [comment]
Abogaría por lo que veas más sencillo.

**Comment by Juanlu001** [comment]
Esto ya está.
