### ISSUE TITLE
Establecer direcciones de contacto

### ISSUE THREAD

**Issue by aaloy** [python-spain/PyConES-2019#40]
* administradores
* contacto genérico
* sponsorización
* prensa?

**Comment by Juanlu001** [comment]
* contact@2019.es.pycon.org
* contact@2019.es.pycon.org
* contact@2019.es.pycon.org
* contact@2019.es.pycon.org

Sea como sea lo van a recibir los mismos :) El único correo diferenciado es contact+finaid@2019.es.pycon.org
