### ISSUE TITLE
Información sobre el lugar

### ISSUE THREAD

**Issue by aaloy** [python-spain/PyConES-2019#41]
Necesito la información básica del lugar donde se desarrolla el evento:

* Nombre
* Localización
* Geoposición

Esto también irá en la información general, pero si la tenemos podemos ir avanzando en otras áreas.

**Comment by Zuriich** [comment]
1. Nombre: Universidad de Alicante. 

- Viernes: Escuela Politécnica 1
- Sabado y Domingo: Aulario 2 y Paraninfo.

2. Localización: Universidad de Alicante, Carretera de San Vicente del Raspeig, s/n, 03690, Alicante 
Geoposición= https://goo.gl/maps/LhgZKnQrAUrdsFYt9
Coordenadas: 38.385135, -0.514486

3. Geoposición de cada una de ellas:

- EPS 1 = https://goo.gl/maps/2Shox2SDGSbLpBRJ7 
Coordenadas: 38.386873, -0.511207
- Aulario 2 = https://goo.gl/maps/S4w1eoLDxfKTmTyY9 
Coordenadas: 38.384729, -0.510174
- Paraninfo = https://goo.gl/maps/sUn2pRmxCKLuWfhg9 
Coordenadas: 38.385226, -0.516909

**Comment by Juanlu001** [comment]
## ¿Se puede dejar el coche?

> Se puede dejar en la uni. Fin de semana igual se cierra el domingo alguna de las puertas pero la de la autovía está abierta 100% seguro. El coche lo puedes sacar cuando quieras y puedes dejarlo allí

Confirma @zuriich

**Comment by Zuriich** [comment]
Medios de Transporte en Alicante

TRAM
Líneas: https://tramalicante.info/#l1
Paradas interesantes: 

- Línea L2 - Universitat (lugar de la conferencia)
- Línea L1, L2, L3 y L4 - MARQ Castillo (Donde está el museo del MARQ y el Castillo Santa Barbara)
- Línea L1, L2, L3, L4 - Mercado (Centro de Alicante)
- Línea L1, L2, L3 y L4 - Luceros (Centro de Alicante, parada más cercana a Renfe) 

BUS

Horario: https://alicante.vectalia.es/wp-content/uploads/sites/2/2018/05/af-FOLLETO-A2-otra-doblez.pdf
Horario Nocturno: https://alicante.vectalia.es/wp-content/uploads/sites/2/2018/11/FOLLETO-LINEAS-NOCTURNAS-ALICANTE.pdf

Líneas Interesantes: 24 y 24N son los buses que llevan desde Alicante hasta la Universidad de Alicante y San Vicente en general.

**Comment by Zuriich** [comment]
En este archivo: https://drive.google.com/file/d/12bF5eC0cCL27ZATgUNf9P9J3TagoMz_8/view?usp=sharing
también están los parkings dentro de la Uni señalizados, se puede ver cuales están más y menos cerca del la conferencia. Durante el viernes por la tarde aún habrá coches ya que hay clase (hay sitio SIEMPRE), pero sábado y domingo no va a costar encontrar parking en ningún sitio.
